Repository guibranco/Sankhya-SDK-dotnet, pull requests merged in 2024-07, with the labels that each got.

#249 ref: convert lowdata to project pattern
  Src/Sankhya/Service/LowData.cs
Labels: enhancement, help wanted, good first issue, .NET, size/XXL, hacktoberfest

#253 Update README.md
  README.md
Labels: size/M, ☑️ auto-merge

#257 Delete techstack.yml
  techstack.yml
Labels: size/L, ☑️ auto-merge

#256 Delete techstack.md
  techstack.md
Labels: size/L, ☑️ auto-merge

#255 Create contributors-readme.yml
  .github/workflows/contributors-readme.yml
Labels: size/S, ☑️ auto-merge

#254 Create pull_request_template.md
  .github/pull_request_template.md
Labels: size/S, ☑️ auto-merge

#262 Update contributors-readme.yml
  .github/workflows/contributors-readme.yml
Labels: size/XS, ☑️ auto-merge

#263 Update contributors-readme.yml
  .github/workflows/contributors-readme.yml
Labels: size/XS, ☑️ auto-merge

#265 [Snyk] Security upgrade CrispyWaffle from 6.1.156 to 6.1.169
  Src/Sankhya/Sankhya.csproj
Labels: size/XS, ☑️ auto-merge

#269 Create sonarcloud-pixeebot.yml
  .github/workflows/sonarcloud-pixeebot.yml
Labels: size/S, ☑️ auto-merge

#270 Create infisical-secrets-check.yml
  .github/workflows/infisical-secrets-check.yml
Labels: size/L, ☑️ auto-merge
